### ISSUE TITLE
ODH Dashboard shows "Not Installed" for all applications. 

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/support#36]
**Describe the bug**
Although the ODH applications are installed and accessible, for some users the [dashboard page](https://odh-dashboard-opf-dashboard.apps.cnv.massopen.cloud/) indicates that they are all unavailable. And applications show the "application not available page".  

**To Reproduce**
1. Go to https://odh-dashboard-opf-dashboard.apps.cnv.massopen.cloud/
2. See image below
![image](https://user-images.githubusercontent.com/4494906/104337711-c5463280-54c3-11eb-92a1-454625305b93.png)

3. Go to https://superset-opf-superset.apps.cnv.massopen.cloud/login/
4. See image below 
![image](https://user-images.githubusercontent.com/4494906/104337881-f0c91d00-54c3-11eb-88f4-2b40ca66baa6.png)

5. After clearing browser cache or using an incognito window, Dashabord shows correctly and applications become available.
![image](https://user-images.githubusercontent.com/4494906/104338308-5e754900-54c4-11eb-9f35-961ea6f7b857.png)

**Expected behaviour**
Should not need to clear cache or use incognito windows to access correct odh dashboard and live applications.

**Comment by HumairAK** [comment]
This looks like an issue with upstream, @tumido wdyt? If so, we should also create an issue there and link this thread.

**Comment by tumido** [comment]
Hm, interesting. :facepalm: 

So the cause of this is that ODH Dashboard deployment runs 2 replicas. Each replica provides a frontend JS bundle and a backend API service which is called on every dashboard load to provide the list of available components in the cluster:

```
curl https://odh-dashboard-opf-dashboard.apps.cnv.massopen.cloud/api/components
```

The problem in this case is that:

<details>
<summary>One replica returns a valid list</summary>

```json
[
  {
    "key": "jupyterhub",
    "label": "JupyterHub",
    "description": "A multi-user version of the notebook designed for companies, classrooms and research labs",
    "img": "images/jupyterhub.svg",
    "docsLink": "https://jupyter.org/hub",
    "enabled": true,
    "namespace": "opf-jupyterhub",
    "link": "https://jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud"
  },
  {
    "key": "argo",
    "label": "Argo",
    "description": "Kubernetes native workflows, events, CI and CD",
    "img": "images/argo.svg",
    "docsLink": "https://argoproj.github.io/",
    "enabled": true,
    "namespace": "opf-argo",
    "link": "http://argo-portal-opf-argo.apps.cnv.massopen.cloud"
  },
  {
    "key": "superset",
    "label": "Superset",
    "description": "A modern, enterprise-ready business intelligence web application",
    "img": "images/superset.svg",
    "docsLink": "https://superset.incubator.apache.org/",
    "enabled": true,
    "namespace": "opf-superset",
    "link": "http://superset-opf-superset.apps.cnv.massopen.cloud"
  },
  {
    "key": "prometheus",
    "label": "Prometheus",
    "description": "Systems monitoring and alerting toolkit",
    "img": "images/prometheus.svg",
    "docsLink": "https://prometheus.io/docs/",
    "enabled": true,
    "namespace": "opf-jupyterhub",
    "link": "http://prometheus-portal-opf-jupyterhub.apps.cnv.massopen.cloud"
  },
  {
    "key": "grafana",
    "label": "Grafana",
    "description": "Visualization and analytics software",
    "img": "images/grafana.svg",
    "docsLink": "https://grafana.com/docs/grafana/latest/",
    "enabled": true,
    "namespace": "opf-monitoring",
    "link": "https://grafana-route-opf-monitoring.apps.cnv.massopen.cloud"
  },
  {
    "key": "spark",
    "label": "Spark",
    "description": "Unified analytics engine for large-scale data processing",
    "img": "images/spark.svg",
    "docsLink": "https://spark.apache.org/docs/latest/",
    "enabled": true
  },
  {
    "key": "seldon",
    "label": "Seldon",
    "description": "Platform for rapidly deploying machine learning models on Kubernetes.",
    "img": "images/seldon.svg",
    "docsLink": "https://docs.seldon.io/",
    "enabled": false
  },
  {
    "key": "kafka",
    "label": "Kafka",
    "description": "Distributed event streaming platform",
    "img": "images/kafka.svg",
    "docsLink": "https://kafka.apache.org/documentation/",
    "enabled": true
  },
  {
    "key": "airflow",
    "label": "Airflow",
    "description": "Platform to programmatically author, schedule, and monitor workflows",
    "img": "images/airflow.svg",
    "docsLink": "https://airflow.apache.org/",
    "enabled": false
  },
  {
    "key": "hue",
    "label": "Hue",
    "description": "Data exploration platform for Hive and S3 storage",
    "img": "images/hue.svg",
    "docsLink": "https://docs.gethue.com/",
    "enabled": true,
    "namespace": "opf-datacatalog",
    "link": "https://hue-opf-datacatalog.apps.cnv.massopen.cloud"
  },
  {
    "key": "thriftserver",
    "label": "Spark SQL Thrift Server",
    "description": "Expose Spark data frames modeled as Hive tables through a JDBC connection",
    "img": "images/spark.svg",
    "docsLink": "https://spark.apache.org/docs/latest/sql-distributed-sql-engine.html",
    "enabled": true,
    "namespace": "opf-datacatalog",
    "link": "http://thriftserver-opf-datacatalog.apps.cnv.massopen.cloud"
  }
]
```
</details>

<details>
<summary>
And the other an invalid</summary>

```json
[
  {
    "key": "jupyterhub",
    "label": "JupyterHub",
    "description": "A multi-user version of the notebook designed for companies, classrooms and research labs",
    "img": "images/jupyterhub.svg",
    "docsLink": "https://jupyter.org/hub",
    "enabled": false
  },
  {
    "key": "argo",
    "label": "Argo",
    "description": "Kubernetes native workflows, events, CI and CD",
    "img": "images/argo.svg",
    "docsLink": "https://argoproj.github.io/",
    "enabled": false
  },
  {
    "key": "superset",
    "label": "Superset",
    "description": "A modern, enterprise-ready business intelligence web application",
    "img": "images/superset.svg",
    "docsLink": "https://superset.incubator.apache.org/",
    "enabled": false
  },
  {
    "key": "prometheus",
    "label": "Prometheus",
    "description": "Systems monitoring and alerting toolkit",
    "img": "images/prometheus.svg",
    "docsLink": "https://prometheus.io/docs/",
    "enabled": false
  },
  {
    "key": "grafana",
    "label": "Grafana",
    "description": "Visualization and analytics software",
    "img": "images/grafana.svg",
    "docsLink": "https://grafana.com/docs/grafana/latest/",
    "enabled": false
  },
  {
    "key": "spark",
    "label": "Spark",
    "description": "Unified analytics engine for large-scale data processing",
    "img": "images/spark.svg",
    "docsLink": "https://spark.apache.org/docs/latest/",
    "enabled": false
  },
  {
    "key": "seldon",
    "label": "Seldon",
    "description": "Platform for rapidly deploying machine learning models on Kubernetes.",
    "img": "images/seldon.svg",
    "docsLink": "https://docs.seldon.io/",
    "enabled": false
  },
  {
    "key": "kafka",
    "label": "Kafka",
    "description": "Distributed event streaming platform",
    "img": "images/kafka.svg",
    "docsLink": "https://kafka.apache.org/documentation/",
    "enabled": false
  },
  {
    "key": "airflow",
    "label": "Airflow",
    "description": "Platform to programmatically author, schedule, and monitor workflows",
    "img": "images/airflow.svg",
    "docsLink": "https://airflow.apache.org/",
    "enabled": false
  },
  {
    "key": "hue",
    "label": "Hue",
    "description": "Data exploration platform for Hive and S3 storage",
    "img": "images/hue.svg",
    "docsLink": "https://docs.gethue.com/",
    "enabled": false
  },
  {
    "key": "thriftserver",
    "label": "Spark SQL Thrift Server",
    "description": "Expose Spark data frames modeled as Hive tables through a JDBC connection",
    "img": "images/spark.svg",
    "docsLink": "https://spark.apache.org/docs/latest/sql-distributed-sql-engine.html",
    "enabled": false
  }
]
```
</details>

This is probably due to the fact that the dashboard is fetching the component list on its startup and it doesn't update this list during the pod lifetime (because it doesn't expect the `kfdef` to change. This is a known limitation to the ODH Dashboard. So, during the MOC outage, one dasboard pod probably started, but couldn't pull the components and therefore it serves an empty list. Restarting this pod will resolve the issue.

**Comment by HumairAK** [comment]
> This is a known limitation to the ODH Dashboard 
Does this meen there's an issue somewhere that exists for this already on the odh repo? 

Anyways, looks like this is resolved -- closing, please re-open if there's more to be added/discussed.

**Comment by tumido** [comment]
> Does this meen there's an issue somewhere that exists for this already on the odh repo?

This is tied to the "unresolved" multi-namespace deployment. I've just consulted the ODH codebase on it and what I've described in the previous comment is not precise. ODH Dashboard can watch a namespace for `kfdef` changes just fine. The problem is with listing all namespaces available - this is done only on the pod startup RN... I've file an issue against our fork here: https://github.com/operate-first/odh-dashboard/issues/3

**Comment by HumairAK** [comment]
Awesome, thanks!

**Comment by MichaelClifford** [comment]
@tumido @HumairAK not sure if others are still experiencing this issue, but I still get the "Application is not available" page if I select any of the applications besides JupyterHub or Hue on the [dashboard page](https://odh-dashboard-opf-dashboard.apps.cnv.massopen.cloud/) without using an incognito window. I have cleared my cache and done the normal browsing data clearing, but the issue seems to persist.  

Let me know if there is any reason other then my browser being stuck in a weird state that might be causing this issue. 

Thanks!

**Comment by tumido** [comment]
Unfortunately it works for me just fine in my current profile, in incognito mode and also in a different browser. Can you try a different browser @MichaelClifford? Is this like a persistent issue or it just happens from time to time?

Can you try investigating via DevTools (available on F12 hotkey in Chrome and Firefox) -> `Network` tab, select `Disable cache` and refresh the page. Then select the `XHR` filter and watch for `components` file traffic:

![image](https://user-images.githubusercontent.com/7453394/109286651-d2747200-7822-11eb-86d9-e378d5cde5f1.png)

Click on the `component` row and check the status. If the status is `200`, select the response tab and message me the response content..
![image](https://user-images.githubusercontent.com/7453394/109286852-15cee080-7823-11eb-8c31-d36f7fc6dc8f.png)

I'll see what we can do. :slightly_smiling_face:

**Comment by MichaelClifford** [comment]
Thanks @tumido 

Looks like my browser was forcing an "https://" url were most of these apps are using "http://". Fixed now, but if any one else has this issue in the future, this [StackExcahnge](https://superuser.com/questions/565409/how-to-stop-an-automatic-redirect-from-http-to-https-in-chrome 
) article helped. Basically come down to following these 2 steps:


1. Go to `chrome://net-internals/#hsts`. Enter `<URL>` under Delete domain security policies and press the Delete button.

2. Now go to `chrome://settings/clearBrowserData`, tick the box Cached images and files and press click the button Clear data.
